sudo: false
language: php

script:
  - echo Pretending to do something nice.

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x $TRAVIS_BUILD_DIR/scripts/deploy.sh && $TRAVIS_BUILD_DIR/scripts/deploy.sh
    on:
      branch: master
